import Head from "next/head";
import { Card, Flex, Text } from "@chakra-ui/react";
import Layout from "../components/Layout";
import Content from "@/components/Content";
import Show from "@/components/Show";

export default function Home() {
  return (
    <>
      <Head>
        <title>MONU-TUBE | HOME</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Layout>
        <Flex
          bg="black"
          minH={"100vh"}
          color={"white"}
          direction={"column"}
          justify={"flex-end"}>
          <Flex justify={"center"} my={"4rem"}>
            <Show />
          </Flex>
          <Flex justify={"center"} mb={"5rem"}>
            <Content />
          </Flex>
        </Flex>
      </Layout>
    </>
  );
}
